---
- name: Download git repos
  git:
    repo: "{{ item.src }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version }}"
    force: "{{ item.force |default(True) }}"
    verify_commit: "{{ item.verify_commit | default(False) }}"
  loop: "{{ additional_nrpe_checks|flatten(levels=1) }}"
  when: item.type == 'git'

- name: set SELinux contexts for checks
  sefcontext:
    target: "{{ item[0].script_path + item[1].script_name }}"
    setype: "{{ item[1].setype }}"
  loop: "{{ additional_nrpe_checks|subelements('commands') }}"
  when: item[1].setype is defined
  notify: SELinux context changed

- name: Genereate facts for additional nrpe checks
  set_fact:
     nrpe_checks: "{{ nrpe_checks |default([]) + [ {
       'command': item[1].command |default( item[1].script_name ),
       'path': item[0].script_path + item[1].script_name |default( item[1].command ),
       'arguments': item[1].arguments |default( nagios_default_argument )
}] }}"
  loop: "{{ additional_nrpe_checks|subelements('commands') }}"
